In [17]:
import pandas as pd
import numpy as np

df = pd.read_csv("raw_data/swiggy_vs_zomato_enriched.csv")
df.head()

,restaurant_id,restaurant_name,city,locality,latitude,longitude,restaurant_type,cuisines,top_selling_dish,distance_from_city_center_km,...,amenities_count,seating_capacity_note,loyalty_program,sustainability_packaging_rating,has_own_website,has_own_app,food_license_verified,year_established,listing_date,days_listed
0,REST000001,Tandoor House,Chennai,Velachery,13.11092,80.16023,Cloud Kitchen,Fast Food; Continental,Fries,0.5,...,6,"Delivery-only, no seating",True,4,False,False,False,2021,2024-09-17,671
1,REST000002,Copper Deck,Delhi,Mayur Vihar,28.80022,77.12131,QSR (Quick Service),Thai,Thai Basil Fried Rice,5.4,...,3,Dine-in available,False,2,False,False,True,2014,2019-08-17,2529
2,REST000003,The Fast House,Ahmedabad,Satellite,22.99754,72.49951,Casual Dining,Fast Food,Cheese Sandwich,6.0,...,4,Dine-in available,False,2,False,False,True,2018,2023-06-06,1140
3,REST000004,Urban Bowl,Chennai,Perambur,13.04000,80.27945,Cafe,Korean; Cafe,Korean Fried Chicken,5.1,...,4,Dine-in available,False,2,False,False,True,2016,2018-10-16,2834
4,REST000005,Golden Kitchen Co.,Mumbai,Lower Parel,19.13642,72.94463,Food Truck,Seafood,Prawn Curry,17.6,...,2,"Delivery-only, no seating",False,5,False,True,False,2016,2019-01-27,2731

In [19]:
df.shape
df.isnull().sum()

restaurant_id                           0
restaurant_name                         0
city                                    0
locality                                0
latitude                                0
longitude                               0
restaurant_type                         0
cuisines                                0
top_selling_dish                        0
distance_from_city_center_km            0
opening_time                            0
closing_time                            0
operating_days_per_week                 0
seating_capacity                        0
swiggy_rating                           0
swiggy_total_reviews                    0
zomato_rating                           0
zomato_total_reviews                    0
average_rating_both_platforms           0
customer_sentiment_score                0
avg_cost_per_person_inr                 0
price_category                          0
swiggy_delivery_fee_inr                 0
zomato_delivery_fee_inr                 0
swiggy_avg_delivery_time_minutes        0
zomato_avg_delivery_time_minutes        0
avg_prep_time_minutes                   0
swiggy_platform_commission_pct          0
zomato_platform_commission_pct          0
swiggy_discount_frequency_pct           0
zomato_discount_frequency_pct           0
swiggy_estimated_monthly_orders         0
zomato_estimated_monthly_orders         0
monthly_order_growth_pct                0
weekend_order_uplift_pct                0
repeat_customer_pct                     0
online_order_share_pct                  0
swiggy_estimated_monthly_revenue_inr    0
zomato_estimated_monthly_revenue_inr    0
swiggy_estimated_net_profit_inr         0
zomato_estimated_net_profit_inr         0
swiggy_market_share_pct                 0
zomato_market_share_pct                 0
platform_performance_better             0
amenities                               0
amenities_count                         0
seating_capacity_note                   0
loyalty_program                         0
sustainability_packaging_rating         0
has_own_website                         0
has_own_app                             0
food_license_verified                   0
year_established                        0
listing_date                            0
days_listed                             0
dtype: int64

Observation: NO duplicate records found.

In [20]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
latitude,8000.0,19.944546,5.449833,12.81534,13.220012,19.047095,23.057630,2.885786e+01
longitude,8000.0,77.031232,4.013453,72.37699,73.747280,77.127450,78.463063,8.851344e+01
distance_from_city_center_km,8000.0,6.068800,4.035941,0.20000,3.100000,5.200000,8.200000,2.200000e+01
operating_days_per_week,8000.0,6.655500,0.567768,5.00000,6.000000,7.000000,7.000000,7.000000e+00
seating_capacity,8000.0,46.227000,39.675011,0.00000,0.000000,44.000000,81.000000,1.200000e+02
swiggy_rating,8000.0,4.371725,0.380041,2.90000,4.100000,4.400000,4.700000,5.000000e+00
swiggy_total_reviews,8000.0,1491.641625,782.091824,218.00000,894.000000,1345.000000,1928.250000,6.651000e+03
zomato_rating,8000.0,4.373325,0.378403,2.90000,4.100000,4.400000,4.700000,5.000000e+00
zomato_total_reviews,8000.0,1491.142750,771.773246,180.00000,901.000000,1345.000000,1935.250000,6.212000e+03
average_rating_both_platforms,8000.0,4.372525,0.363931,3.00000,4.150000,4.400000,4.650000,5.000000e+00
customer_sentiment_score,8000.0,87.356000,8.091026,54.00000,82.000000,88.000000,93.000000,1.000000e+02
avg_cost_per_person_inr,8000.0,549.114875,409.553713,100.00000,296.000000,423.000000,633.000000,3.500000e+03
swiggy_delivery_fee_inr,8000.0,45.560375,17.490472,15.00000,33.000000,42.000000,55.000000,1.200000e+02
zomato_delivery_fee_inr,8000.0,44.381750,16.653016,15.00000,32.000000,41.000000,53.000000,1.150000e+02
swiggy_avg_delivery_time_minutes,8000.0,27.687000,7.140984,12.00000,23.000000,27.000000,32.000000,6.100000e+01
zomato_avg_delivery_time_minutes,8000.0,28.303750,7.459185,12.00000,23.000000,27.000000,32.000000,6.100000e+01
avg_prep_time_minutes,8000.0,21.412250,7.808500,8.00000,15.000000,21.000000,28.000000,3.500000e+01
swiggy_platform_commission_pct,8000.0,21.036787,3.469230,15.00000,18.100000,21.000000,24.100000,2.700000e+01
zomato_platform_commission_pct,8000.0,21.054825,3.467363,15.00000,18.000000,21.100000,24.000000,2.700000e+01
swiggy_discount_frequency_pct,8000.0,18.050625,8.047665,4.00000,11.000000,18.000000,25.000000,3.200000e+01
zomato_discount_frequency_pct,8000.0,18.077750,8.131065,4.00000,11.000000,18.000000,25.000000,3.200000e+01
swiggy_estimated_monthly_orders,8000.0,271.677250,93.471265,70.00000,205.000000,260.000000,325.000000,7.820000e+02
zomato_estimated_monthly_orders,8000.0,271.566125,92.962798,73.00000,204.000000,260.000000,325.000000,8.560000e+02
monthly_order_growth_pct,8000.0,3.058950,8.010012,-24.60000,-2.400000,3.000000,8.500000,3.870000e+01
weekend_order_uplift_pct,8000.0,32.487625,15.857144,5.00000,19.000000,33.000000,46.000000,6.000000e+01
repeat_customer_pct,8000.0,54.443500,10.087890,18.00000,48.000000,55.000000,62.000000,8.300000e+01
online_order_share_pct,8000.0,76.469125,12.438464,55.00000,66.000000,76.000000,87.000000,9.800000e+01
swiggy_estimated_monthly_revenue_inr,8000.0,139133.880500,90438.243044,11970.00000,76283.500000,116835.500000,176999.250000,1.049517e+06
zomato_estimated_monthly_revenue_inr,8000.0,138058.163375,86828.431729,11712.00000,77786.500000,116607.000000,174602.750000,9.140080e+05
swiggy_estimated_net_profit_inr,8000.0,106608.882375,69694.140146,8882.00000,58151.000000,89584.000000,135042.500000,8.296960e+05
zomato_estimated_net_profit_inr,8000.0,105726.849625,66588.328965,9236.00000,59231.000000,89278.500000,134712.250000,6.534150e+05
swiggy_market_share_pct,8000.0,49.989700,8.651764,20.50000,44.100000,50.000000,56.000000,8.190000e+01
zomato_market_share_pct,8000.0,50.010300,8.651764,18.10000,44.000000,50.000000,55.900000,7.950000e+01
amenities_count,8000.0,4.989625,1.988407,2.00000,3.000000,5.000000,7.000000,8.000000e+00
sustainability_packaging_rating,8000.0,2.982625,1.416801,1.00000,2.000000,3.000000,4.000000,5.000000e+00
year_established,8000.0,2018.563250,3.388869,2011.00000,2016.000000,2019.000000,2021.000000,2.026000e+03
days_listed,8000.0,1829.255875,1044.736090,30.00000,915.750000,1833.500000,2743.250000,3.649000e+03

Observation: Numerical columns appear valid with no obvious anomalies

In [22]:
df["listing_date"] = pd.to_datetime(df["listing_date"])
df["listing_date"].dtype

dtype('<M8[ns]')

In [25]:
df.to_csv(
    "processed_data/cleaned_swiggy_vs_zomato.csv",
    index=False
)